
name: ph_lib_${ENV_NAME}

services:

  mongo:
    # image: mongo:3.2
    # image: mongo:3.4
    image: mongo:3.6
    restart: always
    container_name: ph_lib_mongo_${ENV_NAME}
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      # - ../data/mongo_db:/data/db
      # - ../data/mongo_dump:/data/dump
    networks:
      - frontend
      - mongo


  clojure:
    restart: always
    container_name: ph_lib_clojure_${ENV_NAME}
    build: 
      context: ./clojure
      dockerfile: Dockerfile_Clojure
    # ports:
    #   - '9000:9000'
    expose:
      - "9000"
    volumes:
      # - ./app:/usr/src/app
      - ./app/lib:/usr/src/app
    environment:
      IPACS_DOMAIN_NAME: ${IPACS_DOMAIN_NAME}
      COMS_DOMAIN_NAME: ${COMS_DOMAIN_NAME}
      CAP_DOMAIN_NAME: ${CAP_DOMAIN_NAME}
      LIB_DOMAIN_NAME: ${LIB_DOMAIN_NAME}
      CONF_DOMAIN_NAME: ${CONF_DOMAIN_NAME}
      ALBUM_DOMAIN_NAME: ${ALBUM_DOMAIN_NAME}
      VIRTUAL_HOST:
        ${LIB_DOMAIN_NAME},
        # lib.physcon.my, lib.physcon.ru,
    networks:
      - frontend
      - mongo
    links:
      - mongo




networks:
  frontend:
    external: true 
    name: frontend 
  mongo:

volumes:
  mongo-data:

 